[build]
  command = "npm install -g expo-cli && npm install --legacy-peer-deps && npx expo export --platform web"
  publish = "dist"

[dev]
  command = "expo start --web"
  port = 3000
  targetPort = 3000
