[build]
  command = "npm install --legacy-peer-deps && npx expo build --platform web && npx expo export --platform web"
  publish = ".expo/web-build"

[dev]
  command = "expo start --web"
  port = 3000
  targetPort = 3000
